apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-pay-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: google-pay
  template:
    metadata:
      labels:
        app: google-pay
    spec:
      containers:
      - name: google-pay
        image: your-dockerhub-username/google-pay:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: "mongodb://<mongo-host>:27017/googlepay"
---
apiVersion: v1
kind: Service
metadata:
  name: google-pay-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: google-pay
